server:
  port: 9002
spring:
  application:
    name: alibaba-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # ephemeral=true 采用的是 distro 协议-临时实例，ephemeral=false 采用是 raft 协议-持久实例
#        ephemeral: false

management:
  endpoint:
    web:
      exposure:
        include:'*'